# Copyright (c) 2026 Vilhelm Engström
#
# SPDX-License-Identifier: Apache-2.0

version: 2
sphinx:
   configuration: docs/conf.py
python:
   install:
     - requirements: requirements.txt
build:
  os: "ubuntu-24.04"
  apt_packages:
    - cmake
    - doxygen
    - ghostscript
    - graphviz
    - imagemagick
    - latexmk
    - libmagic1
    - libsdl2-dev
    - librsvg2-bin
    - make
    - ninja-build
    - python3-dev
    - python3-pip
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
  tools:
    python: "3.13"
  jobs:
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT
        - cmake -B $READTHEDOCS_OUTPUT -GNinja -DDEPLOY=1 doc
        - ninja -C $READTHEDOCS_OUTPUT
